version: "3.9"

services:
  api:
    build: ./DevopsBasic
    container_name: devopsbasic-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=ASUS-SUDEEPTHI\SQLEXPRESS\;Database=StudentDB;Trusted_Connection=True;TrustServerCertificate=True;


    ports:
      - "5000:5000"
    networks:
      - devopsbasic-net

  web:
    build: ./students-ui
    container_name: devopsbasic-web
    depends_on:
      - api
    ports:
      - "8080:80"
    networks:
      - devopsbasic-net

networks:
  devopsbasic-net:
    driver: bridge

# services:
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5000:8080"

#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile.web
#     ports:
#       - "4200:80"
